### ISSUE TITLE
gettin errors 

### ISSUE THREAD

**Issue by Xezioh** [advancedfx/nSkinz#1]
http://prntscr.com/np2eum

ive been getting most of these with all versions of nSkinz and no1 wants to help me

**Comment by dtugend** [comment]
maybe you should provide more info about your build environment and which exact version you are trying to build.

**Comment by Xezioh** [comment]
add my discord please Xezioh ♥#2035

**Comment by dtugend** [comment]
Please provide more information in this issue instead.
Link to where you got the source from and how you downloaded it.

If you use git, don't forget
`git submodule update`

nSkinz has submodules that are required and it will not build without those.

Downloading the zip from somewhere of the code will not get you those submodules.

**Comment by Xezioh** [comment]
got the original version from https://github.com/namazso/nSkinz downloaded it with github desktop , did the same with ur version

**Comment by dtugend** [comment]
If you download the zip file, then it will be missing sub-modules, you either need to find and download all those folders in deps folder and add them in right place or you need to download with git and use `git submodule update` (I recommend git).

Otherwise you will be missing files / dependencies, which is where most of the errors come from.

**Comment by dtugend** [comment]
Did it work when using git?
I recommend this one: https://git-scm.com/downloads

**Comment by dtugend** [comment]
Closing due to lacking feedback.
