### ISSUE TITLE
its not working i have workshop_default option only why?

### ISSUE THREAD

**Issue by Tycacto** [advancedfx/nSkinz#21]
its not working i have workshop_default option only why?
 plzz help me !!!

**Comment by dtugend** [comment]
* Please make super sure you are using really the latest version:
https://github.com/advancedfx/nSkinz/releases/latest (currently nSkinz-advancedfx-v0.1.13)
We didn't issue an update notifcation, since those still point at the old repository and they currently can not be told apart from screenshot.

* Don't forget to not inject nSkinz.dll in custom loader, but use e.g. `mirv_loadlibrary "C:\path\to\nSkinz.dll"` in console instead.

* Don't forget to hit update and rewind the demo to a round start!
