### ISSUE TITLE
Any tutorial for the setup?

### ISSUE THREAD

**Issue by rvnexe** [advancedfx/nSkinz#37]
Hi, is There any tutorial for compiling and injecting this addon?

**Comment by dtugend** [comment]
It's compiled like the original nSkinz e.g. by opening nSkinz.sln with Visual Studios 2019 (2022 will work too, mabye use 2022), make sure you select the "Desktop Development with C++ component" in Visual Studio Installer, otherwise you won't be able to compile a Win32 **Release** version.  
( https://github.com/advancedfx/nSkinz#usage )

There's also pre-compiled releases here:
https://github.com/advancedfx/nSkinz/releases

nSkinz can be easily loaded e.g. with HLAE:
https://github.com/advancedfx/nSkinz/blob/advancedfx/nSkinz-advancedfx-readme.txt#L1
