### ISSUE TITLE
glove not applying

### ISSUE THREAD

**Issue by tanabae** [advancedfx/nSkinz#4]
sorry for not replying to the last issue.

the gloves still don't work for me, i've tried the method of skipping back to the start of a round and hitting play but nothing happens. (using the latest version)

gloves: 
![Counter-strike  Global Offensive Screenshot 2019 12 10 - 22 41 12 28](https://user-images.githubusercontent.com/57649397/70598051-cb6e2f00-1b9e-11ea-96d9-248ef6578d1d.png)

settings: 
![Counter-strike  Global Offensive Screenshot 2019 12 10 - 22 41 28 75](https://user-images.githubusercontent.com/57649397/70598061-d2953d00-1b9e-11ea-9cf4-fa317603f418.png)

**Comment by dtugend** [comment]
Have you hit update button first?

I am not sure if round start is always enough, it should be, but maybe you even need to rewind to demo start in some cases (?).

I will try the same settings (apart from different XUID) later.

**Comment by dtugend** [comment]
There's indeed a bug with the slick glove.

**Comment by dtugend** [comment]
Try https://github.com/advancedfx/nSkinz/releases/tag/advancedfx-v0.1.8, don't forget to read the list of known problems.

**Comment by tanabae** [comment]
> Try https://github.com/advancedfx/nSkinz/releases/tag/advancedfx-v0.1.8, don't forget to read the list of known problems.

did the slick gloves also not work for you?
do you know any that work?

**Comment by tanabae** [comment]
still doesn't work for me :/

**Comment by dtugend** [comment]
I tested your settings for the glove (with different player / XUID) and they were working.

Please check that you have the default `cl_custom_material_override 1` and not have it on `0`, because that would cause the same problem as on the screenshot.

If that doesn't work either, please provide demo, and the demo time.

**Comment by tanabae** [comment]
the command doesn't do anything for me

**Comment by dtugend** [comment]
> If that doesn't work either, please provide demo, and the demo time.

**Comment by tanabae** [comment]
this is the demo: steam://rungame/730/76561202255233023/+csgo_download_match%20CSGO-9Zsix-Yp74Z-OTAkw-oSrc7-2LJjC

**Comment by dtugend** [comment]
1) You sent the wrong demo, you sent a de_nuke demo. The screenshot shows de_train.
2) You forgot to tell the round or demo time.

**Comment by tanabae** [comment]
the round doesnt really matter, just any time is fine
the same problem happens with that demo
heres the train one anyway: steam://rungame/730/76561202255233023/+csgo_download_match%20CSGO-rV2iz-fwCCS-VERQ6-7yjvr-4rquL

**Comment by dtugend** [comment]
Please try [nSkinz-advancedfx-v0.1.9 or newer](https://github.com/advancedfx/nSkinz/releases/latest)!

**Comment by dtugend** [comment]
Did that new version work for you?

**Comment by tanabae** [comment]
i’m away from home, i can reply in a week

**Comment by dtugend** [comment]
Okay. I didn't put / add anything into it, but just so you know: https://www.virustotal.com/gui/file/71ea55c3947b596e973c27b7968e4efae9147e01afad449debb00b7528a80b41/detection

**Comment by tanabae** [comment]
is it a false positive?

**Comment by dtugend** [comment]
I am not 100% sure, but I think yes:
- Last time I looked through the nSkinz code, I didn't find suspicious things.
- I did not add suspicious things to it myself.
- I am guessing, maybe some sites compile it and offer it together with adware / Trojans / ... which is why it's signature is flagged, or maybe it's just a false positive.

I don't plan on contacting the AV vendors individually regarding the detections of the advancedfx nSkinz compiles to be honest, because it's some work for me and them as well.

You can add an exception in Windows Defender if you come to same conclusion as me.

Otherwise you can still use Migi, someone made a tutorial here, but be aware I didn't create / check the files involved with these at all: https://twitter.com/Andrea68DZN/status/1209781453669711872

**Comment by tanabae** [comment]
holy shit it works now, thank you so much
