### ISSUE TITLE
Question/Request: Add Instructions for compiling

### ISSUE THREAD

**Issue by mrjshzk** [advancedfx/nSkinz#52]
I have tried compiling under VSS2022 but I don't think my compiled build works. Also, the directx sdk mentioned in the readme is from 2010?

**Comment by dtugend** [comment]
The DirectX SDK is part of the Windows SDK nowadays, which is installed as part of the VS 2022 C++ Desktop development workload I think.

Readme is partially outdated sorry.

**Comment by dtugend** [comment]
Additionally the readme still says:
`git clone --recursive https://github.com/advancedfx/nSkinz.git`

This is not correct anymore nowadays, it needs to be instead:
`git clone --recurse-submodules https://github.com/advancedfx/nSkinz.git`

Otherwise you will be missing dependencies that are in sub-modules.

**Comment by mrjshzk** [comment]
Thanks, just proposed a PR

**Comment by dtugend** [comment]
Thanks. Does this solve this solve this issue?

**Comment by mrjshzk** [comment]
Yeah, I was missing dependencies

**Comment by dtugend** [comment]
https://github.com/advancedfx/nSkinz/releases/tag/advancedfx-v0.1.28
(I hope I added no new bugs by trying to fix this.)
