### ISSUE TITLE
I cannot open the GUI by pressing "insert" on my laptop.

### ISSUE THREAD

**Issue by Mmiaox** [advancedfx/nSkinz#56]
Since "insert" is not a single key on my labtop keyboard, it is binded with Num0(they are on the same key), and I cannot open the GUI through Fn+Num0.

I am wondering if I can change the shortcut key to something else.

**Comment by dtugend** [comment]
Which keyboard layout (and keyboard language) are you using in Windows settings?
Can you post a screenshot or schema of your keyboard?

Asking because nSkinz uses a virtual key windows key-code (VK_INSERT), which means if you press the correct combination on they keyboard for Insert, it should work:
https://github.com/advancedfx/nSkinz/blob/4bc248bbe1052d92dc8304143110b76a8d2a893e/src/render.cpp#L323

So either your laptop is broken or you are using a wrong key-board layout in windows or you are pressing the wrong key combination.

The insert key is the key that makes you switch from inserting text at the current location to overwriting (following) text in a text editor usually.

**Comment by dtugend** [comment]
This might help:  
https://www.howtogeek.com/304729/HOW-DO-YOU-PRESS-INSERT-ON-A-KEYBOARD-WITHOUT-AN-INSERT-KEY/

> The 0 Key at the bottom of the number pad on the upper-right corner of your keyboard will function as an Insert Key when Num Lock is turned off. That is why it is labeled with both 0 and Ins on the key itself.

> Note that the Shift Key can act as a temporary toggle for Num Lock when you press one of the keypad keys (just like the Shift Key acts as a toggle for capital letters). Therefore, when Num Lock is on, pressing Shift + Numpad-0 will function as an Insert Key.

**Comment by Mmiaox** [comment]
> This might help: https://www.howtogeek.com/304729/HOW-DO-YOU-PRESS-INSERT-ON-A-KEYBOARD-WITHOUT-AN-INSERT-KEY/
> 
> > The 0 Key at the bottom of the number pad on the upper-right corner of your keyboard will function as an Insert Key when Num Lock is turned off. That is why it is labeled with both 0 and Ins on the key itself.
> 
> > Note that the Shift Key can act as a temporary toggle for Num Lock when you press one of the keypad keys (just like the Shift Key acts as a toggle for capital letters). Therefore, when Num Lock is on, pressing Shift + Numpad-0 will function as an Insert Key.

Thx, it works after I turned off the Number pad.
