### ISSUE TITLE
 fix the problem of glove lighting

### ISSUE THREAD

**Issue by jackKiZhu** [advancedfx/nSkinz#8]
**advancedfx specific?**

Please check that the bug is specific to the advancedfx modded version and not present in the original https://github.com/namazso/nSkinz and otherwise report it there in stead please.

**Describe the bug**
Why does it not work when I open the menu settings?

Can you fix the problem of glove lighting and bandit hair? thank!

**Comment by dtugend** [comment]
This is a bug in the original nSkinz: https://github.com/namazso/nSkinz/issues/204
I already fixed it a bit so that it only happens when the menu / settings are open.

**Comment by NinjaDaddy** [comment]
Can u plz describe how did you fix it? I would like to do that too

**Comment by dtugend** [comment]
@NinjaDaddy

1) Draw only GUI when GUI is active (done only that, since I was in a hurry).

2) I have not done this yet (but plan to do it when I update it next time), but more proper fix (but still lacking proper error handling, since the CreateStateBlock can fail) would be this:

Bellow the lines [188 - 189 in render.cpp](https://github.com/advancedfx/nSkinz/blob/cab6f521f0a5c53cd198e21db0ba1702fde4774d/src/render.cpp#L188):
```
IDirect3DStateBlock9* state;
thisptr->CreateStateBlock(D3DSBT_PIXELSTATE, &state);
```
Add this:
```
state->Capture();
````

Even better idea (apart from adding error handling) if you want to avoid stide effects from CS:GO onto the GUI would be to capture the initial state and use that for the GUI as done by HLAE:
https://github.com/advancedfx/advancedfx/blob/71384d6368ea9fea04fb3253c07661c297b64af4/AfxHookSource/d3d9Hooks.cpp#L4756

**Comment by NinjaDaddy** [comment]
@dtugend

I didn't understand the last paragraph but I did understand the two points at top. Thank u very much and I will try this ASAP

**Comment by dtugend** [comment]
The last paragraph means this:
- CS:GO might put Direct3D9 into a state you don't expect that might mess up the nSkinz GUI.
- A solution for that is to catpure a "clean" state after the device is created / reset and restore this state before drawing the GUI and after that restore the CS:GO captured state again.

Since nSkinz doesn't hook that early usually, a possible solution would be to pretend to CS:GO one-time that the device was lost, so it will reset it and you can capture a "clean" state.

**Comment by NinjaDaddy** [comment]
@dtugend 
So basically copy a small part of HLAE and paste it in nskinz from the link that you gave above?

**Comment by dtugend** [comment]
That paragraph is not solvable with simple copy & paste, maybe ignore it for now, I don't know how to explain it better yet, sorry :(

Drawing the gui only when required like advancedfx nSkinz version + adding state->Capture(); as said in 2) will already solve most important things.

**Comment by NinjaDaddy** [comment]
@dtugend
There's no need to apologise. I'm not that good in programming like you guys are and thank you very much once again for helping us out :).
